# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: OrbiSpace
site_url: https://mydomain.org/mysite
copyright: Copyright &copy; 2020 - 2025 Nikolai Fedorov

nav:
  - Обо мне:
    - index.md
#  - Блог:
#    - blog/index.md
#  - Библиотека:
#    - library/index.md

theme:
  name: material

  font:
    text: Roboto Slab
    code: Roboto Mono

#  icon:
#    previous: fontawesome/solid/angle-left
#    next: fontawesome/solid/angle-right

  features:
    - navigation.tabs
#    - navigation.tabs.sticky
#    - navigation.sections
#    - navigation.expand
#    - navigation.path
#    - navigation.prune

  language: ru

  palette:

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

#plugins:
#  - blog

extra:

  homepage: https://orbitiumnos.github.io/MkDocs_CV/

  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/orbitiumnos/
    - icon: fontawesome/brands/github
      link: https://github.com/orbitiumnos/
    - icon: fontawesome/solid/envelope
      link: mailto:orbitiumnos@yandex.ru

  alternate:
    - name: Русский
      link: /
      lang: ru
#    - name: English
#      link: /en/
#      lang: en
